juguete_new:
    path: /new
    defaults: { _controller: "AppBundle:Juguete:new" }
    methods: POST

juguete_edit:
    path: /edit/{id}
    defaults: { _controller: "AppBundle:Juguete:edit", id:null }
    methods: POST

juguete_upload:
    path: /upload-image/{id}
    defaults: { _controller: "AppBundle:Juguete:upload", id:null }
    methods: POST

juguete_list:
    path: /list
    defaults: { _controller: "AppBundle:Juguete:list" }
    methods: GET

juguete_last:
    path: /last
    defaults: { _controller: "AppBundle:Juguete:last" }
    methods: GET

juguete_detail:
    path: /detail/{id}
    defaults: { _controller: "AppBundle:Juguete:detail", id:null }
    methods: GET

juguete_search:
    path: /search/{search}
    defaults: { _controller: "AppBundle:Juguete:search", search:null }
    methods: GET