juguete_new:
    path: /new
    defaults: { _controller: "AppBundle:Juguete:new" }
    methods: POST

juguete_edit:
    path: /edit/{id}
    defaults: { _controller: "AppBundle:Juguete:edit", id:null }
    methods: POST