BDBundle\Entity\Fabricantes:
    type: entity
    table: fabricantes
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        pais:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
